name: Build and release book
on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release_book:
    name: Build and release book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build book
        uses: ./.github/actions/latex
      - name: Release book
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: free_range_vhdl
          path: free_range_vhdl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
